name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Copy ENV variables
        run: |
          cp /home/envs/.env.frontend .env

      - name: Build Docker image
        run: |
          docker build -t talk-frontend:latest .

      - name: Stop and remove old container
        run: |
          docker stop talk-frontend || true
          docker rm talk-frontend || true

      - name: Run new container
        run: |
          docker run -d \
            --name talk-frontend \
            -p 3000:80 \
            talk-frontend:latest
