name: Deploy

on:
  push:
    branches: ["main"]

concurrency:
  group: "ci-workflow"
  cancel-in-progress: false

jobs:
  build:
    runs-on: self-hosted
    environment: stage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy ENV variables
        run: |
          cp /home/envs/.env.frontend .env

      - name: Build Docker image
        run: |
          docker build -t github_runner/talk-frontend:stage .
          docker tag github_runner/talk-frontend:stage ${{ secrets.DOCKER_REGISTRY_HOST }}/talk-frontend:stage

  push-image:
    runs-on: self-hosted
    needs: build
    environment: stage

    steps:
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login --password-stdin -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}" "${{ secrets.DOCKER_REGISTRY_HOST }}"

      - name: Push Stage Docker image
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY_HOST }}/talk-frontend:stage

      - name: Delete Docker image
        run: |
          docker rmi -f \
            github_runner/talk-frontend:stage \
            ${{ secrets.DOCKER_REGISTRY_HOST }}/talk-frontend:stage

  # restart-stage:
  #   runs-on: self-hosted
  #   needs: push-image
  #   environment: stage

  #   steps:
  #     - name: Restart stage
  #       env:
  #         DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
  #       run: |
  #         echo "$DEPLOY_SSH_KEY" > deploy_key.pem
  #         chmod 600 deploy_key.pem
  #         ssh -i deploy_key.pem -o StrictHostKeyChecking=no root@ifedoseev.ru "cd /root/chat_app/stage && docker compose down && docker compose up -d --build --force-recreate"